bool give_op_jacob   # Request part: Boolean flag to trigger Jacobian calculation
---
float32 jop_00       # Response part: Elements of the Jacobian matrix
float32 jop_01
float32 jop_02
float32 jop_10
float32 jop_11
float32 jop_12
float32 jop_20
float32 jop_21
float32 jop_22